# Generated by Django 4.2.4 on 2023-09-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='notice',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
