# Generated by Django 4.2.4 on 2023-08-27 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_team_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='avatar_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
