# Generated by Django 4.2.4 on 2023-08-30 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='projectrecyclebin',
        #     name='id',
        # ),
        # migrations.RemoveField(
        #     model_name='projectrecyclebin',
        #     name='project_id',
        # ),
        migrations.AddField(
            model_name='projectrecyclebin',
            name='project',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='project.project'),
        ),
    ]
