# Generated by Django 4.2.4 on 2023-08-30 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_projectrecyclebin_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'managed': False},
        ),
        # migrations.RemoveField(
        #     model_name='projectrecyclebin',
        #     name='id',
        # ),
        migrations.RemoveField(
            model_name='projectrecyclebin',
            name='project_id',
        ),
        migrations.AlterField(
            model_name='projectrecyclebin',
            name='project',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='project.project'),
        ),
    ]
