# Generated by Django 4.2.4 on 2023-08-25 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_projectrecyclebin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_id',
        ),
        migrations.RemoveField(
            model_name='projectrecyclebin',
            name='project_id',
        ),
    ]
