# Generated by Django 4.2.4 on 2023-08-30 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_collection_options_remove_projectrecyclebin_id_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='projectrecyclebin',
        #     name='id',
        # ),
        migrations.AlterModelTable(
            name='collection',
            table='project_collection',
        ),
    ]
