# Generated by Django 4.2.4 on 2023-08-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_remove_project_project_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectrecyclebin',
            old_name='creator',
            new_name='deleter',
        ),
        migrations.RemoveField(
            model_name='projectrecyclebin',
            name='team',
        ),
        migrations.AddField(
            model_name='projectrecyclebin',
            name='project_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
