# Generated by Django 4.2.4 on 2023-08-30 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_remove_projectrecyclebin_id_alter_collection_table'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='projectrecyclebin',
        #     name='id',
        # ),
    ]
