# Generated by Django 4.2.4 on 2023-08-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_remove_projectrecyclebin_deleter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectrecyclebin',
            name='creator',
        ),
        migrations.AddField(
            model_name='projectrecyclebin',
            name='creator_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
