# Generated by Django 4.2.4 on 2023-08-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_remove_projectrecyclebin_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='finished_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='height',
            field=models.IntegerField(default=600),
        ),
        migrations.AddField(
            model_name='project',
            name='width',
            field=models.IntegerField(default=800),
        ),
    ]
