# Generated by Django 4.2.4 on 2023-08-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_project_created_time_project_finished_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='isEditing',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='newname',
            field=models.CharField(default='', max_length=10, null=True),
        ),
    ]
