# Generated by Django 4.2.4 on 2023-08-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_project_finished'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='newname',
            new_name='newName',
        ),
        migrations.AlterField(
            model_name='project',
            name='isEditing',
            field=models.BooleanField(default=False),
        ),
    ]
