# Generated by Django 4.2.4 on 2023-08-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_rename_newname_project_newname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrecyclebin',
            name='deleted_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='projectrecyclebin',
            name='expiration_time',
            field=models.DateTimeField(null=True),
        ),
    ]
