# Generated by Django 4.2.4 on 2023-08-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_projectrecyclebin_created_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrecyclebin',
            name='created_time',
            field=models.DateTimeField(null=True),
        ),
    ]
