# Generated by Django 4.2.4 on 2023-08-26 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_alter_projectrecyclebin_created_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='isEditing',
        ),
        migrations.RemoveField(
            model_name='project',
            name='newName',
        ),
    ]
