# Generated by Django 4.2.4 on 2023-08-26 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_remove_project_isediting_remove_project_newname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='height',
        ),
        migrations.RemoveField(
            model_name='project',
            name='width',
        ),
    ]
