# Generated by Django 4.2.4 on 2023-08-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_remove_project_height_remove_project_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_time',
            field=models.DateTimeField(null=True),
        ),
    ]
