# Generated by Django 4.2.4 on 2023-09-02 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_team_notice'),
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='invitation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='team.invitation'),
        ),
    ]
