# Generated by Django 4.1 on 2023-08-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Prototype",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("componentData", models.CharField(max_length=255)),
                ("canvasStyleData", models.CharField(max_length=256)),
                ("all", models.CharField(max_length=4096)),
            ],
            options={"db_table": "prototype",},
        ),
    ]
