# Generated by Django 4.2.4 on 2023-08-27 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prototype',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('componentData', models.TextField(null=True)),
                ('canvasStyleData', models.TextField()),
                ('title', models.CharField(default='title', max_length=64)),
            ],
            options={
                'db_table': 'prototype',
            },
        ),
        migrations.CreateModel(
            name='ProjectPrototype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
                ('prototype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prototype.prototype')),
            ],
            options={
                'db_table': 'project_prototype',
            },
        ),
    ]
