# Generated by Django 4.1 on 2023-08-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prototype", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="prototype",
            name="title",
            field=models.CharField(default="title", max_length=64),
        ),
    ]
