# Generated by Django 4.1 on 2023-08-31 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prototype", "0002_alter_prototype_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prototype",
            name="canvasStyleData",
            field=models.TextField(null=True),
        ),
    ]
