# Generated by Django 4.2.4 on 2023-09-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0002_alter_prototype_title'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='prototype',
        #     name='isPreview',
        #     field=models.BooleanField(default=False),
        # ),
    ]
