# Generated by Django 4.2.4 on 2023-08-27 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='project_id',
            new_name='project',
        ),
    ]
