# Generated by Django 4.2.4 on 2023-08-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_document_content_document_created_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentversion',
            name='version',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
