# Generated by Django 4.2.4 on 2023-08-24 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='name')),
                ('password', models.CharField(max_length=20, verbose_name='password')),
                ('email', models.CharField(max_length=30, null=True, verbose_name='email')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
