# Generated by Django 4.2.4 on 2023-08-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=20, null=True, verbose_name='nickname'),
        ),
        migrations.AddField(
            model_name='user',
            name='truename',
            field=models.CharField(max_length=20, null=True, verbose_name='truename'),
        ),
    ]
