# Generated by Django 4.2.4 on 2023-08-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_email_remove_user_nickname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=30, null=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=20, null=True, verbose_name='nickname'),
        ),
        migrations.AddField(
            model_name='user',
            name='truename',
            field=models.CharField(max_length=20, null=True, verbose_name='truename'),
        ),
    ]
