# Generated by Django 4.2.4 on 2023-08-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_email_user_nickname_user_truename'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCode_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('code', models.CharField(max_length=6)),
                ('expiration_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'VerificationCode_info',
            },
        ),
    ]
