# Generated by Django 4.2.4 on 2023-08-24 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_verificationcode_info_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='truename',
        ),
        migrations.AddField(
            model_name='user',
            name='realname',
            field=models.CharField(max_length=20, null=True, verbose_name='realname'),
        ),
    ]
