# Generated by Django 4.2.4 on 2023-08-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="groupMakerId",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="room",
            name="rank",
            field=models.IntegerField(default=0),
        ),
    ]
