# Generated by Django 4.2.4 on 2023-08-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="isEmoji",
            field=models.BooleanField(default=False),
        ),
    ]
